# Caldera local development configuration
# Used by Athena POC for MITRE ATT&CK technique execution
#
# Reference: https://github.com/mitre/caldera
# License: Apache 2.0
#
# This file will be populated when Caldera integration
# is configured in Phase 6 (SPEC-010).

caldera:
  host: "127.0.0.1"
  port: 8888
  # api_key: set via CALDERA_API_KEY in .env
